language: php

php:
  - 7.3

before_script:
  - sh .travis.install.sh

script:
  - ./vendor/bin/phpunit --disallow-test-output --report-useless-tests --coverage-clover ./clover.xml
  - ./vendor/bin/phpcs --standard=PSR2 ./src ./test

after_script:
  - sh .travis.coverage.sh
