language: php

php:
  - 7.3

before_script:
  - sh .travis.install.sh

script:
  - ./vendor/bin/phpunit --coverage-clover ./clover.xml
  - ./vendor/bin/phpcs
  - ./vendor/bin/psalm
  - ./vendor/bin/infection

after_script:
  - sh .travis.coverage.sh
